# Generated by Django 5.2.4 on 2025-07-25 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FoodApp', '0001_initial'),
        ('GiziApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reccs', to='FoodApp.food')),
                ('simulasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reccs', to='GiziApp.gizi')),
            ],
        ),
    ]
